Parameters:
  HostedZone:
    Type: String
    Default: Z0394676AAXOOA2NV0I3
  DomainName:
    Type: String
    Default: invisi.link

Mappings:
  # From https://github.com/PacktPublishing/AWS-Administration-Cookbook/blob/master/Chapter03/03-hosting-a-static-website.yaml
  RegionMap:
   ca-central-1:
      S3HostedZoneID: Z1QDHH18159H29 
      S3AliasTarget: s3-website.ca-central-1.amazonaws.com

Resources:
  booksS3Redirect:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: !Sub books.${DomainName}
      AccessControl: PublicRead
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: alexanderbird.software/blog/reading-list.html
          Protocol: https
  booksS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: !Ref booksS3Redirect
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::books.${DomainName}/*"
  booksRoute53:
    Type: AWS::Route53::RecordSet
    Properties: 
      HostedZoneId: !Ref HostedZone
      Name: !Sub books.${DomainName}
      Type: A
      AliasTarget:
        HostedZoneId:
          Fn::FindInMap: [ RegionMap, ca-central-1, S3HostedZoneID ]
        DNSName:
          Fn::FindInMap: [ RegionMap, ca-central-1, S3AliasTarget ]
