  apexS3Redirect:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: !Sub ${DomainName}
      AccessControl: PublicRead
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: github.com/alexanderbird/invisi.link
          Protocol: https
  apexS3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: !Ref apexS3Redirect
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${DomainName}/*"
  apexRoute53:
    Type: AWS::Route53::RecordSet
    Properties: 
      HostedZoneId: !Ref HostedZone
      Name: !Sub ${DomainName}
      Type: A
      AliasTarget:
        HostedZoneId:
          Fn::FindInMap: [ RegionMap, ca-central-1, S3HostedZoneID ]
        DNSName:
          Fn::FindInMap: [ RegionMap, ca-central-1, S3AliasTarget ]
