Parameters:
  HostedZone:
    Type: String
  Region:
    Type: String
  AliasToRoute:
    Type: String
  AliasToProtocol:
    Type: String
  AliasFrom:
    Type: String

Mappings:
  # From https://github.com/PacktPublishing/AWS-Administration-Cookbook/blob/master/Chapter03/03-hosting-a-static-website.yaml
  RegionMap:
    ca-central-1:
      S3HostedZoneID: Z1QDHH18159H29 
      S3AliasTarget: s3-website.ca-central-1.amazonaws.com

Resources:
  S3Redirect:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref AliasFrom
      AccessControl: PublicRead
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref AliasToRoute
          Protocol: !Ref AliasToProtocol
  S3PublicBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3Redirect
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${AliasFrom}/*"
  Route53Alias:
    Type: AWS::Route53::RecordSet
    Properties: 
      HostedZoneId: !Ref HostedZone
      Name: !Ref AliasFrom
      Type: A
      AliasTarget:
        HostedZoneId:
          Fn::FindInMap: [ RegionMap, !Ref "Region", S3HostedZoneID ]
        DNSName:
          Fn::FindInMap: [ RegionMap, !Ref "Region", S3AliasTarget ]
